#!/bin/bash

d=$(dirname $0)

cyear=$(date +%Y)
cmonth=$(date +%m)
cday=$(date +%d)

while (( $# > 0 )) ; do case $1 in
	
	-d | --day )
		shift;
		
	 	(( $1 >= 1)) && (( $1 <= 25 )) ||
			{ echo 'Day has to a number between 1 and 25.'; exit; }
		
		day=$(printf %02d $1)
		;;

	-y | --year )
		shift;
		
		(( $1 >= 2015 )) ||
			{ echo "Year has to a number greater than 2015 (first Advent of Code)."; exit; }

		year=$(printf %d $1)
		;;
	* )
		echo "Invalid argument '$1'"
		exit
		;;

esac; shift; done
if [[ "$1" == '--' ]]; then shift; fi

[[ -z "$day" ]] && {
	[[ $cmonth = 12 ]] && day=$cday ||
		{ echo "It's not december and no day was specified."; exit; }
}

: ${year:=$cyear}

[[ $cmonth = 12 ]] && (( $day <= $cday )) && (( $year <= $cyear )) || 
	{ echo "Impatient, aren't we?"; exit; }

i="$d/$year/inputs"
[ -d "$i" ] || mkdir -p "$i"
i="$i/$day"
! [ -f "$i" ] && {
	wget --load-cookies "$d/.config/cookies.txt" \
	     "adventofcode.com/$year/day/$(printf %d $day)/input" \
	     -O "$i" -q &> /dev/null ||
	     	{ echo "Couldn't download input"; rm -r "$i"; exit; }
}
cat "$i"

