#!/bin/bash

d=$(dirname $0)

[[ -n $1 ]] && {
	p=$(printf %02d "$1") &&
	  (( $p >= 1)) &&
	  (( $p <= 31 )) ||
	  { echo 'Not a valid day'; exit; }
}

[ -d "$d/inputs" ] || mkdir "$d/inputs"

day=${p:-$($d/../day)}
i="$d/inputs/$day"
! [ -f "$i" ] && {
	wget --load-cookies "$d/../.config/cookies.txt" \
	     "adventofcode.com/2021/day/$(printf %d $day)/input" \
	     -O "$i" -q &> /dev/null ||
	     	{ echo "Couldn't download input"; exit; }
}
cat "$i"
